import { expect, test } from '@playwright/test';
import { TEXTS } from '../src/lib/texts';

// Un recorrido serial con datos locales: no toca Tiger Data ni consume Gemini.
test('móvil: interpretar, decidir, volver, sin solución e historial', async ({page}) => {
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Capital One Flex'})).toBeVisible();
  await expect(page.getByText(TEXTS.estado.cubiertoTitulo)).toBeVisible();
  const noOverflow = async () => expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await noOverflow();
  await page.screenshot({path:'test-results/mobile-start.png',fullPage:true,animations:"disabled"});
  await expect(page.locator('[data-vista]')).toHaveAttribute('data-vista','cash_calendar');
  await page.getByRole('button',{name:'Pegar mensaje',exact:true}).click();
  await page.getByLabel('¿Qué cambió?').fill('Oigan, la factura de Arcadia se va a atrasar un poco, les aviso luego con calma.');
  await page.getByRole('button',{name:'Ver qué cambia',exact:true}).click();
  await expect(page.getByText(TEXTS.estado.cubiertoTitulo)).toBeVisible();
  await expect(page.getByRole('button',{name:TEXTS.propuesta.confirmar,exact:true})).toHaveCount(0);
  const clarification = page.getByRole('dialog');
  await expect(clarification).toBeVisible();
  await expect(clarification.getByText('Pregunta planteada por Gemini.')).toHaveCount(0);
  await page.keyboard.press('Escape');
  await expect(clarification).toBeVisible();
  await clarification.getByRole('button', {name:'Aceptar',exact:true}).click();
  await expect(clarification).toHaveCount(0);
  await expect(page.getByLabel('¿Qué cambió?')).toBeFocused();
  await page.getByLabel('¿Qué cambió?').fill('Hola, el pago de la factura F-1042 se programó para el 20 de septiembre.');
  await page.getByRole('button',{name:'Ver qué cambia',exact:true}).click();
  const modal = page.getByRole('dialog');
  await expect(modal).toBeVisible();
  await expect(modal.getByText('Antes', {exact:true})).toBeVisible();
  await expect(modal.getByText('Después', {exact:true})).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(modal).toBeVisible();
  await page.mouse.click(2, 2);
  await expect(modal).toBeVisible();
  await page.keyboard.press('Tab');
  expect(await modal.evaluate(element => element.contains(document.activeElement))).toBe(true);
  await page.screenshot({path:'test-results/mobile-proposal.png',fullPage:true,animations:"disabled"});
  await modal.getByRole('button',{name:TEXTS.propuesta.descartar,exact:true}).click();
  await expect(modal).toHaveCount(0);
  await expect(page.getByText(TEXTS.estado.cubiertoTitulo)).toBeVisible();
  await page.getByRole('button',{name:'Ver qué cambia',exact:true}).click();
  await page.getByRole('button',{name:TEXTS.propuesta.confirmar,exact:true}).click();
  await expect(page.getByRole('dialog',{name:TEXTS.propuesta.titulo})).toHaveCount(0);
  await expect(page.getByRole('dialog').getByRole('heading',{level:2})).toContainText('Necesitas');
  await page.screenshot({path:'test-results/mobile-alternatives-modal.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Cerrar y decidir después',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Necesitas cubrir'})).toBeVisible();
  const compare=page.locator('[data-seccion="plan_comparison"]');
  async function openPlans() {
    if (await compare.getAttribute('data-protagonista') !== 'si') await compare.locator('summary').first().click();
  }
  await expect(compare).toHaveAttribute('data-protagonista','si');
  await openPlans();
  await expect(compare.getByText(TEXTS.planes.condicionalAviso).first()).toBeVisible();
  await noOverflow();
  const reject = () => compare.getByRole('button',{name:new RegExp(TEXTS.planes.excluirPrefijo)}).first();
  await page.screenshot({path:'test-results/mobile-plans.png',fullPage:true,animations:"disabled"});
  const before = await page.request.get('/api/scenario').then(r=>r.json());
  await reject().click();
  await expect(page.getByRole('button',{name:'Deshacer último cambio'})).toBeVisible();
  // Cambiar de vista no agrega un paso a deshacer.
  await page.getByRole('button',{name:'Ver quién me debe',exact:false}).click();
  await expect(page.locator('[data-vista]')).toHaveAttribute('data-vista','receivables');
  await page.screenshot({path:'test-results/mobile-receivables.png',fullPage:true,animations:'disabled'});
  await expect.poll(async()=> (await page.request.get('/api/scenario').then(r=>r.json())).scenario.id).not.toBe(before.scenario.id);
  await page.getByRole('button',{name:'Deshacer último cambio',exact:true}).click();
  await expect.poll(async()=> (await page.request.get('/api/scenario').then(r=>r.json())).scenario.id).toBe(before.scenario.id);
  await expect(page.getByRole('status')).toContainText('Deshecho:');
  await expect(page.getByRole('status')).toContainText('Alternativas:');
  // La UI restaurada puede seguir operando sobre el servidor, sin conflicto.
  for (let i=0;i<5;i++) {
    if (await page.getByRole('heading',{name:'Con estas opciones no alcanza'}).count()) break;
    await openPlans();
    await reject().click();
    await expect(page.getByText('Revisando tus opciones…')).toHaveCount(0);
  }
  await expect(page.getByRole('heading',{name:'Con estas opciones no alcanza'})).toBeVisible();
  await expect(page.locator('[data-seccion="plan_comparison"]')).toHaveCount(0);
  await expect(page.locator('[data-vista]')).toHaveAttribute('data-vista','constraints');
  await page.screenshot({path:'test-results/mobile-blocked.png',fullPage:true,animations:'disabled'});
  await noOverflow();
  await page.getByRole('button',{name:'Revisar mis cambios',exact:false}).click();
  const history=page.locator('[data-seccion="history"]');
  await expect(history).toHaveAttribute('data-protagonista','si');
  await expect(history.getByText('Antes faltaban')).toBeVisible();
  await expect(history.getByText('Después faltan')).toBeVisible();
  await noOverflow();
  await page.screenshot({path:'test-results/mobile-final.png',fullPage:true,animations:"disabled"});
  const undoHistory = await page.request.get('/api/history').then(r=>r.json());
  const dateAction = undoHistory.entries.find((entry:{eventType:string;undo?:{available:boolean}})=>entry.eventType === 'receivable_rescheduled' && entry.undo?.available);
  expect(dateAction).toBeTruthy();
  const dateCard = page.locator(`[data-history-action="${dateAction.id}"]`);
  await dateCard.getByRole('button',{name:'Deshacer esta acción',exact:true}).click();
  await expect(page.getByText(TEXTS.estado.cubiertoTitulo)).toBeVisible();
  const restoredHistory = await page.request.get('/api/scenario').then(r=>r.json());
  expect(restoredHistory.result.baseline.shortfallCents).toBe(0);
  expect(restoredHistory.result.excludedActionIds.length).toBeGreaterThan(0);
  await expect(dateCard.getByRole('button',{name:'Deshacer esta acción',exact:true})).toBeDisabled();
  await expect(dateCard).toContainText('Acción deshecha.');
  await noOverflow();
  await page.screenshot({path:'test-results/mobile-history-undo.png',fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:1440,height:1000});
  await noOverflow();
  await page.screenshot({path:'test-results/desktop-final.png',fullPage:true,animations:"disabled"});
  await page.getByRole('button',{name:'Reiniciar ejemplo',exact:true}).click();
  await expect(page.getByText(TEXTS.estado.cubiertoTitulo)).toBeVisible();
  await expect(page.getByRole('button',{name:'Deshacer último cambio'})).toHaveCount(0);
  const clean = await page.request.get('/api/scenario').then(r=>r.json());
  expect(clean.result.excludedActionIds).toEqual([]);
  expect(clean.scenario.revision).toBe(0);
  const cleanHistory = await page.request.get('/api/history').then(r=>r.json());
  expect(cleanHistory.entries.some((entry:{undo?:unknown})=>entry.undo)).toBe(false);
  await page.getByLabel('Factura pendiente de cobro').selectOption('inv-a');
  await page.getByLabel('¿Qué pasará con el cobro?').selectOption('delay');
  await page.getByLabel('Nueva fecha esperada').fill('2026-09-20');
  await page.getByRole('button',{name:'Ver qué cambia',exact:true}).click();
  await page.getByRole('button',{name:TEXTS.propuesta.confirmar,exact:true}).click();
  await expect(page.getByRole('heading',{name:'Necesitas cubrir'})).toBeVisible();
  const replay = await page.request.get('/api/scenario').then(r=>r.json());
  expect(replay.result.plans.map((plan:{id:string})=>plan.id)).toEqual(['plan:S1','plan:C1']);
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('dialog').getByRole('button',{name:'Quiero intentar esta opción'}).first().click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Opción elegida para negociar'})).toBeVisible();
  const afterChoice = await page.request.get('/api/scenario').then(r=>r.json());
  expect(afterChoice.result.id).toBe(replay.result.id);

});
